apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "coding_challenge_chart.fullname" . }}-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: k8s-storage-class
